export { Facebook } from "./Facebook";
export { Instagram } from "./Instagram";
export { TripAdvisor } from "./TripAdvisor";
export { GoogleIcon } from "./GoogleIcon";
export { ShoppingDelete } from "./shopping/ShoppingDelete";
export { ShoppingCheck } from "./shopping/ShoppingCheck";
export { Izipay } from "./Izipay";
export { Paypal } from "./Paypal";
export { WhatsApp } from "./Whatsapp";
